---
title: "columnselectApp"
date: "`r Sys.Date()`"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

<!-- output: -->
<!--   rmdformats::material: -->
<!--     highlight: kate -->

```{r setup, include=FALSE}
# xaringan::inf_mr() ----
library(knitr)
library(rmdformats)
library(tidyverse)
library(devtools)
library(hrbrthemes)
library(fs)
library(shiny)
library(reactable)
# figs folder
fs::dir_create('img')
# Global options
knitr::opts_chunk$set(
  # cache = FALSE # cache data
  echo = TRUE, # show/hide all code
  # results = "hide", # hide results
  tidy = FALSE, # cleaner code printing
  comment = "#> ", # better console printing
  eval = FALSE, # turn this to FALSE stop code chunks from running
  message = TRUE, # show messages
  warning = FALSE, # show warnings
  size = "tiny", # size of the text
  fig.path = "https://raw.githubusercontent.com/mjfrigaard/shinymod/main/img/", # location of figure files
  fig.height = 7.5, # height of figures
  fig.width = 10 # width of figures
) 
# knit options
knitr::opts_knit$set(
  width = 78,
  progress = FALSE
)
# base options
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
  max.print = 999999,
  scipen = 100000000
)
```

<!-- badges: start -->
<!-- badges: end -->

## columnSelectApp

The goal of `columnSelectApp` is to select a dataset from a list, display the available columns, choose which columns to display, and render the selected columns. 

## colselUI

```{r colselUI}
colselUI <- function(id) {
  tagList(
    sidebarLayout(
      sidebarPanel(
        # x variable
        selectInput(
          inputId = NS(namespace = id, id = "dataset"),
          label = "Dataset", selected = "",
          choices = names(palmerpenguins::penguins)
        ),
        # y variable
        selectInput(
          inputId = NS(namespace = id, id = "y_var"),
          label = "Y column", selected = "bill_length_mm",
          choices = names(palmerpenguins::penguins)
        ),
        # color
        selectInput(
          inputId = NS(namespace = id, id = "color"),
          label = "Color column", selected = "species",
          choices = names(palmerpenguins::penguins)
        )
      ),
      mainPanel(
        # table
        reactableOutput(
          outputId =
            NS(namespace = id, id = "table")
        ),
        # some space
        br(), br(), br(),
        # values
        tags$strong("data ", tags$code("reactiveValues:")),
        verbatimTextOutput(
          outputId =
            NS(namespace = id, id = "value")
        )
      )
    )
  )
}
```


## colselServer

```{r colselServer}
colselServer <- function(id) {
    
  moduleServer(id = id, module = function(input, output, session) {
    # data
    data <- reactive({
        ds538[[input$cols]]
    })
    
    observeEvent(data(), {
      updateSelectInput(session = session, inputId = "cols", 
          choices = names(ds538[[input$cols]]), 
          selected = names(ds538[["unisex_names"]])[1])
    })

    # table display
    output$data_display <- reactable::renderReactable({
      reactable::reactable(
        data = data(),
        # reactable settings ------
        defaultPageSize = 10,
        resizable = TRUE,
        highlight = TRUE,
        height = 350,
        wrap = FALSE,
        bordered = TRUE,
        searchable = TRUE,
        filterable = TRUE
      )
    })

    # reactive values
    output$values <- shiny::renderPrint({
      all_values <- reactiveValuesToList(x = input, 
                                         all.names = TRUE)
      values <- all_values[str_detect(names(all_values), "reactable", TRUE)]
      print(values)
    })
  })
}
```

